name: Run Project Tests

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'The project number (1, 2, 3a, 3b, or 4) to debug'
        required: true
        default: '1'

  release:
    types: [created, edited]

jobs:
  verify:
    name: 'Verification'
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: 'Setup Java 15'
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: 'Test Project'
        uses: usf-cs212-spring2021/action-test-project@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ github.event.inputs.project }}
